#!/usr/bin/env python3
# coding=UTF-8
import os
import sys
import timeit

from acados_template import AcadosOcp, AcadosOcpSolver, AcadosSimSolver
import numpy as np
import scipy.linalg

import casadi as ca
from acados_template import AcadosModel

class Optimizer(object):
    def __init__(self, gazebo = False, x0 = None):
        self.solver, self.integrator, self.T, self.N, self.t_horizon = self.create_solver()

    def create_solver(self, config_path='config/mpc_config25.yaml'):
        model = AcadosModel()
        v = ca.SX.sym('v')
        delta = ca.SX.sym('delta')
        controls = ca.vertcat(v, delta)
        x = ca.SX.sym('x')
        y = ca.SX.sym('y')
        psi = ca.SX.sym('psi')
        states = ca.vertcat(x, y, psi)
        self.L = 0.258
        rhs = [v*ca.cos(psi), v*ca.sin(psi), v/self.L*ca.tan(delta)]

        f = ca.Function('f', [states, controls], [ca.vcat(rhs)], ['state', 'control_input'], ['rhs'])
        x_dot = ca.SX.sym('x_dot', len(rhs))
        f_impl = x_dot - f(states, controls)

        model.f_expl_expr = f(states, controls)
        model.f_impl_expr = f_impl
        model.x = states
        model.xdot = x_dot
        model.u = controls
        model.p = []

        current_path = os.path.dirname(os.path.realpath(__file__))
        path = os.path.join(current_path, config_path)
        with open(path, 'r') as f:
            config = yaml.safe_load(f)
        model.name = config['name']
        T = config['T']
        N = config['N']
        constraint_name = 'constraints'
        cost_name = 'costs'
        t_horizon = T * N
        # constraints
        self.v_max = config[constraint_name]['v_max']
        self.v_min = config[constraint_name]['v_min']
        self.delta_max = config[constraint_name]['delta_max']
        self.delta_min = config[constraint_name]['delta_min']
        self.x_min = config[constraint_name]['x_min']
        self.x_max = config[constraint_name]['x_max']
        self.y_min = config[constraint_name]['y_min']
        self.y_max = config[constraint_name]['y_max']
        self.v_ref = config[constraint_name]['v_ref']
        # costs
        self.x_cost = config[cost_name]['x_cost']
        self.y_cost = config[cost_name]['y_cost']
        self.yaw_cost = config[cost_name]['yaw_cost']
        self.v_cost = config[cost_name]['v_cost']
        self.steer_cost = config[cost_name]['steer_cost']
        self.delta_v_cost = config[cost_name]['delta_v_cost']
        self.delta_steer_cost = config[cost_name]['delta_steer_cost']
        self.costs = np.array([self.x_cost, self.yaw_cost, self.v_cost, self.steer_cost, self.delta_v_cost, self.delta_steer_cost])
        Q = np.array([[self.x_cost, 0.0, 0.0],[0.0, self.y_cost, 0.0],[0.0, 0.0, self.yaw_cost]])*1
        R = np.array([[self.v_cost, 0.0], [0.0, self.steer_cost]])*1

        nx = model.x.size()[0]
        nu = model.u.size()[0]
        ny = nx + nu
        n_params = len(model.p)

        os.chdir(os.path.dirname(os.path.realpath(__file__)))
        acados_source_path = os.environ['ACADOS_SOURCE_DIR']
        sys.path.insert(0, acados_source_path)
        ocp = AcadosOcp()
        ocp.acados_include_path = acados_source_path + '/include'
        ocp.acados_lib_path = acados_source_path + '/lib'
        ocp.model = model
        ocp.dims.N = N
        ocp.solver_options.tf = t_horizon
        ocp.dims.np = n_params
        ocp.parameter_values = np.zeros(n_params)

        ocp.cost.cost_type = 'LINEAR_LS'
        ocp.cost.cost_type_e = 'LINEAR_LS'
        ocp.cost.W = scipy.linalg.block_diag(Q, R)
        ocp.cost.W_e = Q
        ocp.cost.Vx = np.zeros((ny, nx))
        ocp.cost.Vx[:nx, :nx] = np.eye(nx)
        ocp.cost.Vu = np.zeros((ny, nu))
        ocp.cost.Vu[-nu:, -nu:] = np.eye(nu)
        ocp.cost.Vx_e = np.eye(nx)

        ocp.constraints.lbu = np.array([self.v_min, self.delta_min])
        ocp.constraints.ubu = np.array([self.v_max, self.delta_max])
        ocp.constraints.idxbu = np.array([0, 1])
        ocp.constraints.lbx = np.array([self.x_min, self.y_min])
        ocp.constraints.ubx = np.array([self.x_max, self.y_max])
        ocp.constraints.idxbx = np.array([0, 1])

        x_ref = np.zeros(nx)
        u_ref = np.zeros(nu)
        ocp.constraints.x0 = x_ref
        ### 0--N-1
        ocp.cost.yref = np.concatenate((x_ref, u_ref))
        ### N
        ocp.cost.yref_e = x_ref

        ocp.solver_options.qp_solver = 'PARTIAL_CONDENSING_HPIPM'
        ocp.solver_options.hessian_approx = 'GAUSS_NEWTON'
        ocp.solver_options.integrator_type = 'ERK'
        ocp.solver_options.print_level = 0
        ocp.solver_options.nlp_solver_type = 'SQP_RTI'

        json_file = os.path.join('./'+model.name+'_acados_ocp.json')
        initialize_solver_time = timeit.default_timer()
        solver = AcadosOcpSolver(ocp, json_file=json_file)
        integrator = AcadosSimSolver(ocp, json_file=json_file)
        return solver, integrator, T, N, t_horizon
    
    def update_and_solve(self):
        self.target_waypoint_index = self.find_next_waypoint()
        idx = self.target_waypoint_index
        self.next_trajectories = self.state_refs[idx:idx + self.N + 1]
        self.next_controls = self.input_refs[idx:idx + self.N]
        xs = self.state_refs[idx]
        self.solver.set(self.N, 'yref', xs)
        for j in range(self.N):
            if self.target_waypoint_index+j >= self.state_refs.shape[0]:
                self.solver.set(j, 'yref', np.concatenate((self.state_refs[-1], np.zeros(2))))
            else:
                self.solver.set(j, 'yref', np.concatenate((self.next_trajectories[j], self.next_controls[j])))# 设置当前循环x0 (stage 0)
        if self.last_u is None:
            self.last_u = np.zeros(2)
        self.last_u[0] = self.next_controls[0, 0]
        self.solver.set(0, 'yref', np.concatenate((self.next_trajectories[j], self.last_u)))
        self.solver.set(0, 'lbx', self.current_state)
        self.solver.set(0, 'ubx', self.current_state)
        status = self.solver.solve()
        if status != 0 :
            print('ERROR!!! acados acados_ocp_solver returned status {}. Exiting.'.format(status))
            return None
        next_u = self.solver.get(0, 'u')
        self.counter += 1
        self.last_u = next_u
        return next_u
    
    def integrate_next_states(self, u_res=None):
        self.integrator.set('x', self.current_state)
        self.integrator.set('u', u_res)
        status_s = self.integrator.solve()
        if status_s != 0:
            raise Exception('acados integrator returned status {}. Exiting.'.format(status_s))
        self.current_state = self.integrator.get('x')
        self.t0 += self.T
    
    def update_current_state(self, x, y, yaw):
        # Ensure target_waypoint_index is within bounds
        if self.target_waypoint_index < len(self.state_refs):
            # Extract the reference yaw at the current target waypoint
            ref_yaw = self.state_refs[self.target_waypoint_index, 2]
            # Adjust yaw to minimize its difference with ref yaw
            while yaw - ref_yaw > np.pi:
                yaw -= 2 * np.pi
            while yaw - ref_yaw < -np.pi:
                yaw += 2 * np.pi
        self.current_state = np.array([x, y, yaw])
    def update_real_state(self, x, y, yaw):
        if self.target_waypoint_index < len(self.state_refs):
            ref_yaw = self.state_refs[self.target_waypoint_index, 2]
            while yaw - ref_yaw > np.pi:
                yaw -= 2 * np.pi
            while yaw - ref_yaw < -np.pi:
                yaw += 2 * np.pi
        self.real_state = np.array([x, y, yaw])
    def find_closest_waypoint(self):
        # min_index = max(0, self.last_waypoint_index - self.limit)
        # max_index = min(self.num_waypoints - 1, self.last_waypoint_index + self.limit)
        # distances = np.linalg.norm(np.vstack((self.waypoints_x[min_index:max_index], self.waypoints_y[min_index:max_index])).T - self.current_state[:2], axis=1)
        distances = np.linalg.norm(np.vstack((self.waypoints_x, self.waypoints_y)).T - self.current_state[:2], axis=1)
        index = np.argmin(distances)
        return index, distances[index]
    def find_next_waypoint(self):
        # start = timeit.default_timer()
        closest_idx, dist_to_waypoint = self.find_closest_waypoint()

        # self.last_waypoint_index = self.target_waypoint_index
        # if dist_to_waypoint < self.region_of_acceptance:
        #     self.target_waypoint_index += 1
        # if closest_idx > self.target_waypoint_index:
        #     self.target_waypoint_index = closest_idx + 1
        # elif closest_idx + self.limit/3 < self.target_waypoint_index:
        #     self.target_waypoint_index = closest_idx + 1
        # return min(self.target_waypoint_index, len(self.waypoints_x) - 1)

        if dist_to_waypoint < self.region_of_acceptance:
            if closest_idx - self.last_waypoint_index < 15:
                self.last_waypoint_index = max(self.last_waypoint_index, closest_idx+1)
            else:
                # print("here: ", closest_idx, self.last_waypoint_index, closest_idx - self.last_waypoint_index)
                closest_idx = self.last_waypoint_index
                # self.last_waypoint_index += 1
        else:
            if closest_idx - self.last_waypoint_index > 15:
                # print("here2: ", closest_idx, self.last_waypoint_index, closest_idx - self.last_waypoint_index)
                closest_idx = self.last_waypoint_index + 1
                # closest_idx = self.last_waypoint_index 
            # If not within the region of acceptance, take smaller steps forward in the waypoint list
            self.last_waypoint_index += 1
        target_idx = max(self.last_waypoint_index, closest_idx)
        # print this: std::cout << "cur:" << current_state[0] << "," << current_state[1] << "," << current_state[2] << ", closest_idx:" << closest_idx << ", closest:" << state_refs(closest_idx, 0) << "," << state_refs(closest_idx, 1) << "," << state_refs(closest_idx, 2) << ", dist: " << dist<<  ", last_waypoint_index:" << last_waypoint_index << ", target_idx:" << target_waypoint_index << std::endl;
        # print("cur:", self.current_state, ", closest_idx: ", closest_idx, ", closest: ", self.state_refs[closest_idx], "dist_to_waypoint: ", dist_to_waypoint,  ", last_waypoint_index: ", self.last_waypoint_index, ", target_idx: ", target_idx)
        # print("find_next_waypoint time: ", timeit.default_timer() - start)
        return min(target_idx, len(self.waypoints_x) - 1)
    def draw_result(self, stats, xmin=None, xmax=None, ymin=None, ymax=None, objects=None, car_states=None):
        if xmin is None:
            xmin = self.x_min
            xmax = self.x_max
            ymin = self.y_min
            ymax = self.y_max
        print("saving as ", self.export_fig)
        # objects = [
        #     {'type': 'stop_sign', 'pose': [3, 3]},
        #     {'type': 'traffic_light', 'pose': [7, 8]},
        #     {'type': 'parking_spot', 'pose': [10, 2]},
        #     {'type': 'crosswalk', 'pose': [12, 4]},
        #     {'type': 'roundabout', 'pose': [5, 10]}
        # ]
        Draw_MPC_tracking(self.u_c, init_state=self.init_state, 
                        robot_states=self.xx, ref_states = self.x_refs, export_fig=self.export_fig, waypoints_x=self.waypoints_x, 
                        waypoints_y=self.waypoints_y, stats = stats, costs = self.costs, xmin=xmin, xmax=xmax, ymin=ymin, ymax=ymax,
                        times = self.t_c, objects=objects, car_states=car_states)
    def compute_stats(self):
        ## after loop
        print("iter: ", self.mpciter)
        t_v = np.array(self.index_t)
        try:
            print("mean solve time: ",t_v.mean(), "max: ", t_v.max(), "min: ", t_v.min(), "std: ", t_v.std(), "median: ", np.median(t_v))
            print((time.time() - self.start_time)/(self.mpciter))
        except:
            print("error when computing time")
        # print the control input, keep 2 digits after the decimal point
        u_c = np.array(self.u_c).reshape(-1, 2)

        print("average kappa: ", np.mean(self.kappa))
        average_speed = np.mean(u_c[:, 0])
        average_steer = np.mean(u_c[:, 1])
        
        delta_u_c = np.diff(u_c, axis=0)
        average_delta_speed = np.mean(np.abs(delta_u_c[:, 0]))
        average_delta_steer = np.mean(np.abs(delta_u_c[:, 1]))
        
        print(f"Average speed: {average_speed:.4f} m/s")
        print(f"Average steer angle: {average_steer:.4f} rad")
        print(f"Average change in speed: {average_delta_speed:.4f} m/s²")
        print(f"Average change in steer angle: {average_delta_steer:.4f} rad/s")

        average_x_error = np.mean(np.abs(self.x_errors))
        average_y_error = np.mean(np.abs(self.y_errors))
        self.yaw_errors = np.array(self.yaw_errors)
        self.yaw_errors = np.arctan2(np.sin(self.yaw_errors), np.cos(self.yaw_errors))
        average_yaw_error = np.mean(np.abs(self.yaw_errors))

        print(f"Average x error: {average_x_error:.4f} m")
        print(f"Average y error: {average_y_error:.4f} m")
        print(f"Average yaw error: {average_yaw_error:.4f} rad")

        stats = [average_speed, average_steer, average_delta_speed, average_delta_steer, average_x_error, average_y_error, average_yaw_error]
        return stats
   
if __name__ == '__main__':
    argparser = argparse.ArgumentParser(description='MPC controller')
    argparser.add_argument('--save_path', action='store_true', help='save path')
    args = argparser.parse_args()

    running = True

    x0 = np.array([10, 13.29, np.pi])
    # mpc = Optimizer(x0=x0)
    mpc = Optimizer()
    
    if running:
        mpc.target_waypoint_index = 0
        while True:
            if mpc.target_waypoint_index >= mpc.num_waypoints-1 or mpc.mpciter > 1000:
            # if mpc.target_waypoint_index >= 375:
                break
            t = time.time()
            mpc.x_errors.append(mpc.current_state[0] - mpc.next_trajectories[0, 0])
            mpc.y_errors.append(mpc.current_state[1] - mpc.next_trajectories[0, 1])
            mpc.x_refs.append(mpc.next_trajectories[0, :])
            mpc.yaw_errors.append(mpc.current_state[2] - mpc.next_trajectories[0, 2])
            # print("cur: ", np.around(mpc.current_state, decimals=2), ", ref: ", np.around(mpc.next_trajectories[0, :], decimals=2), ", ctrl: ", np.around(mpc.next_controls[0, :], decimals=2), ", idx: ", mpc.target_waypoint_index)
            t_ = time.time()
            u_res = mpc.update_and_solve()
            t2 = time.time()- t_
            if u_res is None:
                break
            mpc.index_t.append(t2)
            mpc.t_c.append(mpc.t0)
            mpc.u_c.append(u_res)
            mpc.integrate_next_states(u_res)
            # u_res = u_res[0]
            # print("time: ", t2, "u_res: ", u_res)
            mpc.xx.append(mpc.current_state)
            mpc.mpciter = mpc.mpciter + 1
        stats = mpc.compute_stats()
        # save current states and controls as txt
        # np.savetxt('x.txt', mpc.xx, fmt='%.8f')
        # np.savetxt('u.txt', mpc.u_c, fmt='%.8f')
        # park_offset = 0.#95
        # mpc.current_state = np.array([park_offset, 0, np.pi])
        # mpc.go_straight(park_offset)
        # mpc.park()
        # mpc.exit_park()
        print("done")
        # mpc.draw_result(stats, -35, 35, -35, 35)
        mpc.draw_result(stats, -2, 22, -2, 16)
        # mpc.draw_result(stats, -1, 5, -1, 2)

# mean solve time:  0.000547633899913563 max:  0.0007941722869873047 min:  0.00040841102600097656 std:  6.495536205623692e-05 median:  0.0005583763122558594
# 0.0005843510756363997
# average kappa:  0.711998927789088
# Average speed: 1.0142 m/s
# Average steer angle: 0.0634 rad
# Average change in speed: 0.0417 m/s²
# Average change in steer angle: 0.0311 rad/s
# Average x error: 0.0460 m
# Average y error: 0.0429 m
# Average yaw error: 0.0898 rad

# mean solve time:  0.0005373664192862801 max:  0.0008776187896728516 min:  0.0003986358642578125 std:  6.203874916996816e-05 median:  0.0005426406860351562
# 0.0005724191903829813
# average kappa:  0.711998927789088
# Average speed: 1.0143 m/s
# Average steer angle: 0.0650 rad
# Average change in speed: 0.0439 m/s²
# Average change in steer angle: 0.0357 rad/s
# Average x error: 0.0464 m
# Average y error: 0.0418 m
# Average yaw error: 0.0881 rad