= Useful commands for Cluj 2026

JETSON IPs
- BoschFMC: 192.168.50.110
- hotspot:

COMMAND LAPTOP IP (DELL)
- hotspot: 10.89.16.85
- BoschFMC:192.168.50.175

== SSH to Jetson over USB-c

ssh scandy@192.168.55.1

# Make sure the WiFi radio is on
nmcli radio wifi on

# Scan for available networks
nmcli device wifi list

# Connect to one
sudo nmcli device wifi connect "BoschFMC" password "bosch23581321"
sudo nmcli device wifi connect "slsecret357" password "simonli357"

# Create Persistant Connection
sudo nmcli connection modify "BoschFMC" connection.autoconnect yes

# Show Jetson IP
ip a show wlan0

sudo nvpmodel -m 0      # set power mode to MAXN (max performance profile)
sudo jetson_clocks 

#Monitor serial
sudo minicom -D /dev/ttyACM0 -b 115200D
#or if device changed
sudo minicom -D /dev/ttyACM1 -b 115200D

#controller launch
roslaunch control controller.launch camera:=true ip:=192.168.50.175 use_gps:=false real:=true realsense:=true
with traffic and gps
roslaunch control controller.launch camera:=true ip:=192.168.50.175 use_gps:=true real:=true realsense:=true use_traffic_server:=true gps_points:=25 gps_id:=10

#gui 
rosrun gui main.py
-------------------------------
= useful commands
d3t2
258722448dccdcda9d0e7b520ce2573326d8f758
final morning
d16c468c97c69d00dacb04f36cc2f22388e3dde9
d4t1
bf1e3a149ae61239ca95fc34f156121fab161dc7

BOSCHFMC
roslaunch control controller.launch camera:=true ip:=192.168.50.175 use_gps:=false real:=true realsense:=true
with traffic and gps
roslaunch control controller.launch camera:=true ip:=192.168.50.175 use_gps:=true real:=true realsense:=true use_traffic_server:=true gps_points:=25 gps_id:=10

HUAWEIP30
roslaunch control controller.launch camera:=true ip:=192.168.43.143 use_gps:=false real:=true realsense:=true v:=35

== jetson ip
10.121.116.244 (old)
10.122.218.202 (new)

== webm to mp4
input="screen-capture"
ffmpeg -i ~/Downloads/"$input".webm ~/Downloads/"$input".mp4

== speed up video
input="8ruler2"
speed=1.334
ffmpeg -i "$HOME/Downloads/$input".mp4 -filter_complex "[0:v]setpts=PTS/$speed[v]" -map "[v]" -an "$HOME/Downloads/${input}_fast.mp4"

== trim video
input="output"
start_time="00:04:15"
end_time="00:04:35"

ffmpeg -ss "$start_time" -to "$end_time" \
-i "$HOME/Downloads/${input}.webm" \
-c:v libx264 -c:a aac \
"$HOME/Downloads/${input}_trimmed.mp4"

== crop video (e.g., top-left 640x360 region)
input="output"
ffmpeg -i "$HOME/Downloads/${input}.webm" \
-vf "crop=640:360:0:0" \
-c:v libx264 -c:a aac \
"$HOME/Downloads/${input}_cropped.mp4"

== mp4 to gif 
input="output"
ffmpeg -i "$input".mp4 -vf "fps=20,scale=iw:ih:flags=lanczos" -c:v gif "$input".gif

== disable screen inversion when connected to realsense
```bash
gsettings set org.gnome.settings-daemon.plugins.orientation active false
```

== simulator run
- simulator:
cd to the folder where the simulator is located
```bash
roslaunch sim_pkg run3.launch
```

- path planner:
```bash
rosrun planning path2.py
```

- detection:
```bash
roslaunch perception cameraNode.launch newlane:=false use_tcp:=true
```

- gui:
```bash
rosrun gui gui2.py
```

- control:
```bash
roslaunch control controller.launch sign:=true lane:=true v:=25 use_tcp:=true
```

== real run
- path planner:
```bash
rosrun planning path2.py
```

- detection:
```bash
roslaunch perception cameraNode.launch newlane:=false real:=true realsense:=true use_tcp:=true
```

- gui:
```bash
rosrun perception gui.py
or
rosrun perception gui2.py # if using tcp
```


- control:
```bash
roslaunch control controller.launch sign:=true lane:=true v:=25 real:=true use_tcp:=true
```

== debugging gui

```bash
gdb --args python3 src/perception/scripts/gui.py
run
```

== realsense params

=== depth
rostopic echo /camera/depth/camera_info
header: 
  seq: 25
  stamp: 
    secs: 1737595205
    nsecs: 353224754
  frame_id: "camera_depth_optical_frame"
height: 480
width: 640
distortion_model: "plumb_bob"
D: [0.0, 0.0, 0.0, 0.0, 0.0]
K: [388.25311279296875, 0.0, 323.0739440917969, 0.0, 388.25311279296875, 237.99143981933594, 0.0, 0.0, 1.0]
R: [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]
P: [388.25311279296875, 0.0, 323.0739440917969, 0.0, 0.0, 388.25311279296875, 237.99143981933594, 0.0, 0.0, 0.0, 1.0, 0.0]
binning_x: 0
binning_y: 0
roi: 
  x_offset: 0
  y_offset: 0
  height: 0
  width: 0
  do_rectify: False
---
=== color
rostopic echo /camera/color/camera_info
header: 
  seq: 0
  stamp: 
    secs: 1737595265
    nsecs: 930911779
  frame_id: "camera_color_optical_frame"
height: 480
width: 640
distortion_model: "plumb_bob"
D: [0.0, 0.0, 0.0, 0.0, 0.0]
K: [607.4056396484375, 0.0, 322.97222900390625, 0.0, 607.0582885742188, 244.39398193359375, 0.0, 0.0, 1.0]
R: [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]
P: [607.4056396484375, 0.0, 322.97222900390625, 0.0, 0.0, 607.0582885742188, 244.39398193359375, 0.0, 0.0, 0.0, 1.0, 0.0]
binning_x: 0
binning_y: 0
roi: 
  x_offset: 0
  y_offset: 0
  height: 0
  width: 0
  do_rectify: False
FOV (deg): (55.56294646186197, 43.14253845277586)
---

- mbed
mbed-tools compile -m B_L4S5I_IOT01A -t GCC_ARM
st-flash erase

