= useful commands

roslaunch perception cameraNode.launch real:=true realsense:=true lane:=false ip:=10.121.105.18
roslaunch control controller.launch real:=true ip:=10.121.105.18 use_gps:=false lane:=false
roslaunch control controller.launch real:=true ip:=10.121.105.18 use_gps:=false real:=true realsense:=true

== webm to mp4
input="screen-capture"
ffmpeg -i ~/Downloads/"$input".webm ~/Downloads/"$input".mp4

== speed up video
input="8ruler2"
speed=1.334
ffmpeg -i "$HOME/Downloads/$input".mp4 -filter_complex "[0:v]setpts=PTS/$speed[v]" -map "[v]" -an "$HOME/Downloads/${input}_fast.mp4"

== trim video
input="output"
start_time="00:04:15"
end_time="00:04:35"

ffmpeg -ss "$start_time" -to "$end_time" \
-i "$HOME/Downloads/${input}.webm" \
-c:v libx264 -c:a aac \
"$HOME/Downloads/${input}_trimmed.mp4"

== crop video (e.g., top-left 640x360 region)
input="output"
ffmpeg -i "$HOME/Downloads/${input}.webm" \
-vf "crop=640:360:0:0" \
-c:v libx264 -c:a aac \
"$HOME/Downloads/${input}_cropped.mp4"

== mp4 to gif
input="output"
ffmpeg -i "$input".mp4 -vf "fps=20,scale=iw:ih:flags=lanczos" -c:v gif "$input".gif

== disable screen inversion when connected to realsense
```bash
gsettings set org.gnome.settings-daemon.plugins.orientation active false
```

== simulator run
- simulator:
cd to the folder where the simulator is located
```bash
roslaunch sim_pkg run3.launch
```

- path planner:
```bash
rosrun planning path2.py
```

- detection:
```bash
roslaunch perception cameraNode.launch newlane:=false use_tcp:=true
```

- gui:
```bash
rosrun gui gui2.py
```

- control:
```bash
roslaunch control controller.launch sign:=true lane:=true v:=25 use_tcp:=true
```

== real run
- path planner:
```bash
rosrun planning path2.py
```

- detection:
```bash
roslaunch perception cameraNode.launch newlane:=false real:=true realsense:=true use_tcp:=true
```

- gui:
```bash
rosrun perception gui.py
or
rosrun perception gui2.py # if using tcp
```


- control:
```bash
roslaunch control controller.launch sign:=true lane:=true v:=25 real:=true use_tcp:=true
```

== debugging gui

```bash
gdb --args python3 src/perception/scripts/gui.py
run
```

== realsense params

=== depth
rostopic echo /camera/depth/camera_info
header: 
  seq: 25
  stamp: 
    secs: 1737595205
    nsecs: 353224754
  frame_id: "camera_depth_optical_frame"
height: 480
width: 640
distortion_model: "plumb_bob"
D: [0.0, 0.0, 0.0, 0.0, 0.0]
K: [388.25311279296875, 0.0, 323.0739440917969, 0.0, 388.25311279296875, 237.99143981933594, 0.0, 0.0, 1.0]
R: [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]
P: [388.25311279296875, 0.0, 323.0739440917969, 0.0, 0.0, 388.25311279296875, 237.99143981933594, 0.0, 0.0, 0.0, 1.0, 0.0]
binning_x: 0
binning_y: 0
roi: 
  x_offset: 0
  y_offset: 0
  height: 0
  width: 0
  do_rectify: False
---
=== color
rostopic echo /camera/color/camera_info
header: 
  seq: 0
  stamp: 
    secs: 1737595265
    nsecs: 930911779
  frame_id: "camera_color_optical_frame"
height: 480
width: 640
distortion_model: "plumb_bob"
D: [0.0, 0.0, 0.0, 0.0, 0.0]
K: [607.4056396484375, 0.0, 322.97222900390625, 0.0, 607.0582885742188, 244.39398193359375, 0.0, 0.0, 1.0]
R: [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]
P: [607.4056396484375, 0.0, 322.97222900390625, 0.0, 0.0, 607.0582885742188, 244.39398193359375, 0.0, 0.0, 0.0, 1.0, 0.0]
binning_x: 0
binning_y: 0
roi: 
  x_offset: 0
  y_offset: 0
  height: 0
  width: 0
  do_rectify: False
FOV (deg): (55.56294646186197, 43.14253845277586)
---

- mbed
mbed-tools compile -m B_L4S5I_IOT01A -t GCC_ARM
st-flash erase

