real:
  lane_relocalize: true
  sign_relocalize: true
  intersection_relocalize: false
  has_light: false
  use_kf: false
  # sign_lon_offset: -0.01
  sign_lon_offset: -0.0
  # sign_lon_offset_slope: 0.05
  sign_lon_offset_slope: 0.0
  # sign_lat_offset: 0.015
  sign_lat_offset: 0.0
  change_lane_offset_scaler: 1.2
  min_dist_to_car: 0.3 # min distance from ego car front to other car back
  min_tailing_dist: 0.3 # max distance from ego car front to other car back
  max_light_dist: 0.75
  max_sign_dist: 1.5
  min_sign_dist: 0.3
  highway_cooldown: 3.0
  sign_cooldown: 3.0
  cumulative_confidence_thresholds: [3.5, 2.5, 2.5, 2.5, 2.5, 2.5, 3.5, 2.5, 2.5, 2.5, 2.5, 2.5, 18, 2.5, 2.5, 2.5]
  recency_thresholds: [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5]
  stop_duration: 1.5
  sign_localization_threshold: 0.537 #0.357
  sign_localization_orientation_threshold: 45.0 # degrees
  lane_localization_threshold: 0.9
  lane_localization_orientation_threshold: 7.53 # degrees
  intersection_localization_threshold: 0.753
  intersection_localization_orientation_threshold: 15.0 # degrees
  parking_base_thresh: 0.1
  parking_base_speed: -0.2
  parking_base_yaw_target: 0.23 # times pi
  cw_speed_ratio: 0.85
  hw_speed_ratio: 1.25
  pixel_center_offset: 0
  constant_distance_to_intersection_at_detection: 0.3725
  NORMAL_SPEED: 0.20
  odom_rate: 50
  pedestrian_distance: 0.75
  pedestrian_threshold: 0.35

sim:
  lane_relocalize: true
  sign_relocalize: true
  intersection_relocalize: false
  has_light: false
  use_kf: false
  sign_lon_offset: 0.0
  sign_lon_offset_slope: 0.0
  sign_lat_offset: 0.0
  change_lane_offset_scaler: 1.2
  min_dist_to_car: 0.2 # min distance from ego car front to other car back
  min_tailing_dist: 0.3 # max distance from ego car front to other car back
  max_light_dist: 0.75
  max_sign_dist: 1.5
  min_sign_dist: 0.3
  highway_cooldown: 3.0
  sign_cooldown: 3.0
  cumulative_confidence_thresholds: [3.5, 2.5, 2.5, 2.5, 2.5, 2.5, 3.5, 2.5, 2.5, 2.5, 2.5, 2.5, 18, 2.5, 2.5, 2.5]
  recency_thresholds: [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5] # in seconds
  stop_duration: 1.5
  sign_localization_threshold: 0.537 #0.357
  sign_localization_orientation_threshold: 45.0 # degrees
  lane_localization_threshold: 0.1
  lane_localization_orientation_threshold: 7.53 # degrees
  intersection_localization_threshold: 1.5
  intersection_localization_orientation_threshold: 15.0 # degrees
  parking_base_yaw_target: 0.26 # times pi
  parking_base_speed: -0.2
  parking_base_thresh: 0.1
  cw_speed_ratio: 0.85
  hw_speed_ratio: 1.25
  pixel_center_offset: 0
  constant_distance_to_intersection_at_detection: 0.3725
  NORMAL_SPEED: 0.23
  odom_rate: 50
  pedestrian_distance: 0.75
  pedestrian_threshold: 0.35
