name: mobile_robot_25
T: 0.1
N: 40
constraints:
  v_max: 0.4
  v_min: -0.4
  v_ref: 0.25

  delta_max: 0.3578
  delta_min: -0.3578
  x_min: -1.0
  x_max: 22.0
  y_min: -1.0
  y_max: 16.0

costs:
  y_cost: 2
  x_cost: 2
  yaw_cost: 0.5
  v_cost: 1 
  steer_cost: 0.
  delta_v_cost: 0.25
  delta_steer_cost: 0.5