name: mobile_robot_32
T: 0.1
N: 40
l_r: 0.103
l_f: 0.155
wheelbase: 0.258

constraints:
  v_max: 0.5
  v_min: -0.5
  v_ref: 0.32

  delta_max: 0.3578
  delta_min: -0.3578
  x_min: -3.0
  x_max: 25.0
  y_min: -3.0
  y_max: 19.0

costs:
  y_cost: 2
  x_cost: 2
  yaw_cost: 0.5
  v_cost: 1 
  steer_cost: 0.
  delta_v_cost: 0.25
  delta_steer_cost: 0.5