name: mobile_robot
# T: 0.1
# N: 50
# T: 0.05
# N: 100
T: 0.05
# T: 0.125
N: 40
# T: 0.25
# N: 100
constraints:
  v_max: 1.8
  v_min: -1.8
  v_ref: 1.3

  delta_max: 0.42
  delta_min: -0.42
  x_min: -50.0
  x_max: 50.0
  y_min: -50.0
  y_max: 50.0

costs:
  y_cost: 2
  x_cost: 2
  yaw_cost: 0.5
  v_cost: 1 
  steer_cost: 0.2
  delta_v_cost: 0.25
  delta_steer_cost: 0.5