resolution: 300
width_m: 0.8
near_m: 0.48 # relative to camera
far_m: 2.0

window_min_pixels: 10
window_margin_multiplier: 4
n_windows: 9
pixel_to_meter_y_slope: 0.003138337
pixel_to_meter_y_intercept: 0.3778245
stopline_distance_threshold: 0.5 # distance to front of car

adaptive_threshold_block_size: 199
adaptive_threshold_c: -25