resolution: 750
width_m: 0.8
near_m: 0.48 # relative to car
far_m: 1.5

window_min_pixels: 8
window_margin_multiplier: 4
window_fit_min_ratio: 0.8
# n_windows: 18
window_height: 0.1
stopline_distance_threshold: 0.5 # distance to front of car

adaptive_threshold_block_size: 199
adaptive_threshold_c: -25
