enum PRIMITIVES {
    FORCE_STOP,
    PARKING_SIGN_DETECTED,
    PARKING_COUNT,
    PARKING_SUCCESS,
    PARKING_COMPLETE,
    TRAFFIC_LIGHT_DETECTED,
    STOP_SIGN_DETECTED,
    PEDESTRIAN_DETECTED,
    DESTINATION_REACHED,
};
